version: "3"

services:
  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - local-data:/data
  db:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5431:5432
  rabbitmq:
    image: rabbitmq:4.0-management
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  local-data:  
  pgdata: